Визуальная подсветка ключевых слов, слов из названия в тексте работы
EduardBlees/Master-s-thesis pull request #106
Opened 2020-08-05 23:17 UTC by levi218

resolved #76

2020-08-06 15:24 UTC, zmm requested changes
Протестировал на двух файлах - приложил их к PR.

Общее впечатление - находятся не все ключевые слова, а для PDF появляются лишние. Ниже скриншоты проверок

Результат для PDF
![image](https://user-images.githubusercontent.com/717575/89550255-131e8680-d812-11ea-834a-c5ce31f0ccd7.png)

Результат для Docx
![image](https://user-images.githubusercontent.com/717575/89550277-1c0f5800-d812-11ea-88ce-e14955a505a0.png)

[paper_kutsenok.docx](https://github.com/OSLL/sw-auto/files/5035858/paper_kutsenok.docx)
[paper_kutsenok.pdf](https://github.com/OSLL/sw-auto/files/5035859/paper_kutsenok.pdf)

2020-08-06 21:48 UTC, levi218 commented
Теперь должно работать.
Для pdf:
- Если названия разделов не указаны, будет взят текст, расположенный между ключевым словом "ключевые слова" и концом строки. 
- Если указаны имена разделов, будет взят текст между ключевым словом и первым найденным именем раздела.

2020-08-06 23:07 UTC, levi218 commented
теперь должно работать.
Для pdf:
- Если названия разделов не указаны, будет взят текст, расположенный между ключевым словом "ключевые слова" и концом строки. Если указаны имена разделов, будет взят текст между ключевым словом и первым найденным именем раздела.

2020-08-07 12:19 UTC, zmm commented
Исправьте конфликты

2020-08-07 12:38 UTC, levi218 commented
Исправил

2020-08-07 13:55 UTC, zmm commented
vood@vood-ThinkPad-T470:~/ws/sw-auto/SciencePaperAnalyzer$ docker-compose build --no-cache && docker-compose up
mongo uses an image, skipping
mongo-express uses an image, skipping
Building web-analyzer
Step 1/31 : FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
 ---> e7e3b238011c
Step 2/31 : WORKDIR /app
 ---> Running in dbef60aba971
Removing intermediate container dbef60aba971
 ---> 1ad51021e900
Step 3/31 : EXPOSE 80
 ---> Running in 6e56c54eafcf
Removing intermediate container 6e56c54eafcf
 ---> 312d9ac016ef
Step 4/31 : EXPOSE 443
 ---> Running in df68fb9ddaec
Removing intermediate container df68fb9ddaec
 ---> b965be6f310c
Step 5/31 : FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
 ---> 2357b6790b9d
Step 6/31 : WORKDIR /src
 ---> Running in b6588fd7cf27
Removing intermediate container b6588fd7cf27
 ---> c7c696dd4cd9
Step 7/31 : COPY ["TestWebApp/WebPaperAnalyzer.csproj", "TestWebApp/"]
 ---> 498ce9ba29d6
Step 8/31 : COPY ["TextExtractor/TextExtractor.csproj", "TextExtractor/"]
 ---> 6626ddb5a4d1
Step 9/31 : COPY ["PaperAnalyzer/PaperAnalyzer.csproj", "PaperAnalyzer/"]
 ---> ff79a61cf2f5
Step 10/31 : COPY ["LangAnalyzerStd.Postagger/LangAnalyzerStd.Postagger.csproj", "LangAnalyzerStd.Postagger/"]
 ---> cb9ec8967459
Step 11/31 : COPY ["LangAnalyzerStd.Core/LangAnalyzerStd.Core.csproj", "LangAnalyzerStd.Core/"]
 ---> ad4ff1018023
Step 12/31 : COPY ["LangAnalyzerStd.Morphology/LangAnalyzerStd.Morphology.csproj", "LangAnalyzerStd.Morphology/"]
 ---> 790f8df55f6f
Step 13/31 : COPY ["LangAnalyzerStd.SentenceSplitter/LangAnalyzerStd.SentenceSplitter.csproj", "LangAnalyzerStd.SentenceSplitter/"]
 ---> 9bbb6974ee89
Step 14/31 : COPY ["LangAnalyzerStd.Сrfsuite/LangAnalyzerStd.Сrfsuite.csproj", "LangAnalyzerStd.Сrfsuite/"]
 ---> 01738fde4cc5
Step 15/31 : COPY ["AnalyzeResults/AnalyzeResults.csproj", "AnalyzeResults/"]
 ---> 99082ff4e19b
Step 16/31 : COPY ["Test/Test.csproj", "Test/"]
 ---> 0eb95ac9b717
Step 17/31 : COPY . .
 ---> b2aaee0108d6
Step 18/31 : RUN dotnet test -c Release
 ---> Running in e0258ba402a8
Models/DbInstance.cs(35,23): warning CS0108: 'ResultCriterion.UseOfPersonalPronounsCost' hides inherited member 'ResultScoreSettings.UseOfPersonalPronounsCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(36,23): warning CS0108: 'ResultCriterion.UseOfPersonalPronounsErrorCost' hides inherited member 'ResultScoreSettings.UseOfPersonalPronounsErrorCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(37,40): warning CS0108: 'ResultCriterion.UseOfPersonalPronounsGrading' hides inherited member 'ResultScoreSettings.UseOfPersonalPronounsGrading'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(38,28): warning CS0108: 'ResultCriterion.UseOfPersonalPronounsGradingType' hides inherited member 'ResultScoreSettings.UseOfPersonalPronounsGradingType'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(39,23): warning CS0108: 'ResultCriterion.SourceNotReferencedCost' hides inherited member 'ResultScoreSettings.SourceNotReferencedCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(40,23): warning CS0108: 'ResultCriterion.SourceNotReferencedErrorCost' hides inherited member 'ResultScoreSettings.SourceNotReferencedErrorCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(41,40): warning CS0108: 'ResultCriterion.SourceNotReferencedGrading' hides inherited member 'ResultScoreSettings.SourceNotReferencedGrading'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(42,28): warning CS0108: 'ResultCriterion.SourceNotReferencedGradingType' hides inherited member 'ResultScoreSettings.SourceNotReferencedGradingType'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(43,23): warning CS0108: 'ResultCriterion.ShortSectionCost' hides inherited member 'ResultScoreSettings.ShortSectionCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(44,23): warning CS0108: 'ResultCriterion.ShortSectionErrorCost' hides inherited member 'ResultScoreSettings.ShortSectionErrorCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(45,40): warning CS0108: 'ResultCriterion.ShortSectionGrading' hides inherited member 'ResultScoreSettings.ShortSectionGrading'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(46,28): warning CS0108: 'ResultCriterion.ShortSectionGradingType' hides inherited member 'ResultScoreSettings.ShortSectionGradingType'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(47,23): warning CS0108: 'ResultCriterion.PictureNotReferencedCost' hides inherited member 'ResultScoreSettings.PictureNotReferencedCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(48,23): warning CS0108: 'ResultCriterion.PictureNotReferencedErrorCost' hides inherited member 'ResultScoreSettings.PictureNotReferencedErrorCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(49,40): warning CS0108: 'ResultCriterion.PictureNotReferencedGrading' hides inherited member 'ResultScoreSettings.PictureNotReferencedGrading'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(50,28): warning CS0108: 'ResultCriterion.PictureNotReferencedGradingType' hides inherited member 'ResultScoreSettings.PictureNotReferencedGradingType'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(51,23): warning CS0108: 'ResultCriterion.TableNotReferencedCost' hides inherited member 'ResultScoreSettings.TableNotReferencedCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(52,23): warning CS0108: 'ResultCriterion.TableNotReferencedErrorCost' hides inherited member 'ResultScoreSettings.TableNotReferencedErrorCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(53,40): warning CS0108: 'ResultCriterion.TableNotReferencedGrading' hides inherited member 'ResultScoreSettings.TableNotReferencedGrading'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(54,28): warning CS0108: 'ResultCriterion.TableNotReferencedGradingType' hides inherited member 'ResultScoreSettings.TableNotReferencedGradingType'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(55,23): warning CS0108: 'ResultCriterion.MaxScore' hides inherited member 'ResultScoreSettings.MaxScore'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(56,44): warning CS0108: 'ResultCriterion.ForbiddenWords' hides inherited member 'ResultScoreSettings.ForbiddenWords'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(57,23): warning CS0108: 'ResultCriterion.ForbiddenWordsCost' hides inherited member 'ResultScoreSettings.ForbiddenWordsCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(58,23): warning CS0108: 'ResultCriterion.ForbiddenWordsErrorCost' hides inherited member 'ResultScoreSettings.ForbiddenWordsErrorCost'. Use the new keyword if hiding was intended. [/src/TestWebApp/WebPaperAnalyzer.csproj]
Models/DbInstance.cs(59,40): warning CS0108: 'R [...]

2020-08-07 14:26 UTC, levi218 commented
моя ошибка при исправлении конфликта. извините.

2020-08-07 15:15 UTC, zmm requested changes
Отлично, в целом все работает, остались мелкие штрихи:
1. Выделение совпадений в тексте должно оставаться, когда пользователь нажал на ключевое слово или фрагмент названия. Сейчас выделение исчезает, когда убираешь курсор.
2. В названии могут быть знаки препинания 
![image](https://user-images.githubusercontent.com/717575/89659510-a9b57b00-d8d8-11ea-9643-7b08d8fc5869.png)
3. Для приложенного файла не находятся ключевые слова трудозатраты и, аналитика трудозатрат

2020-08-07 17:15 UTC, levi218 commented
2. знак должен быть отделен от слова или удален?

2020-08-19 14:07 UTC, zmm commented
Знак препинания должен быть отделен

2020-08-25 09:56 UTC, merged