added keywords mentioning criterion
EduardBlees/Master-s-thesis pull request #110
Opened 2020-08-25 21:48 UTC by levi218

2020-08-28 13:16 UTC, zmm requested changes
1. Создал критерий оценивания как в приложенном файле.

[criteria.zip](https://github.com/OSLL/sw-auto/files/5142241/criteria.zip)

При попытке его отредактировать (http://localhost:4444/StudentTeacher/EditDeleteCriterion?name=keywords) - ошибка

Error.
An error occurred while processing your request.
Request ID: 0HM2BADRR563G:0000001B

Error message:

2. Проверяю указанным критерием документ в котором я намеренно добавил два несуществующих ключевых слова
[paper_kutsenok (1-я копия).docx](https://github.com/OSLL/sw-auto/files/5142231/paper_kutsenok.1-.docx)

2020-08-28 13:16 UTC, zmm commented on SciencePaperAnalyzer/AnalyzeResults/Presentation/BooleanCriterion.cs
> +            return Value? "Доволен" : "Неудовлетворен";
Предлагаю такие значения
Выполнен / Не выполнен

2020-08-28 18:31 UTC, levi218 commented
первая ошибка, вероятно, связана с редактированием набора критериев без словаря запрещенных слов (мне пришлось загрузить пустой словарь, а затем выбрать его при добавлении набора критериев). Это также упоминается в #108 . Чтобы избежать конфликта, вы хотите создать новые issues, исправить это в этом pr или в pr #108 ?

2020-09-01 11:28 UTC, zmm commented
Поправьте, пожалуйста, конфликт.

2020-09-01 12:04 UTC, levi218 commented
конфликт исправлен

2020-09-01 12:50 UTC, zmm commented
Проверяю файл статьи по критерию из файла. В статье намеренно добавил два несуществующих ключевых слова, однако статья получаем максимум баллов

![image](https://user-images.githubusercontent.com/717575/91853403-cee4a180-ec6a-11ea-8330-f8a22f72fd0c.png)
 
[bug8.zip](https://github.com/OSLL/sw-auto/files/5156267/bug8.zip)

2020-09-04 10:26 UTC, merged