Criteria range validator
EduardBlees/Master-s-thesis pull request #111
Opened 2020-08-27 22:13 UTC by levi218

сначала проверьте pr #110 
Задача - показать возможный диапазон по стоимости и весу.
Я предлагаю использовать sliders, которые служат той же цели (пользователь не может вводить недопустимые значения). Если это нежелательно, текстовые поля можно вернуть, добавив строку кода.

2020-08-28 13:57 UTC, zmm requested changes
Нгуен, я приношу свои извинения - к сожалению, я был невнимателен при постановке данной задачи, так как она устарела. Основная проблема - устаревание и несовершенство текущей системы оценивания. Предлагаю в данном PR ее скорректировать и соответственно изменить интерфейс. 

Идея в следующем - для всех критериев, кроме воды, тошноты, ципфа и ключевых слов необходимо заменить статичное значение штрафа  на произвольный набор порогов и штрафов для каждого из порогов.  Для примера возьмем критерий "Нет ссылки на источник". Предположим, что для данного критерия указан вес 10. Тогда в новой модели ему можно задать такую систему порогов (это для примера - идея в том, что пользователи будут вводить свои наборы):

1 не указанная ссылка на источник ( == одно нарушение критерия) - штраф 2 балла
2-5 нарушений - штраф 5 баллов
6-7 нарушений - штраф 8 баллов
более 7 нарушений - штраф 10 баллов

Я бы предложил такую структуру данных для этого примера:
{ 1: 2, 5: 5, 7:8 }
где ключ это верхняя граница порога, а значение - штраф. 

Для текущего интерфейса я бы предложил минимальные правки:
- вертикальный слайдер оставляем,
- добавить выделение серым тех критериев, которые не участвуют в оценке,
- использовать горизонтальный слайдер для задания диапазонов,
- динамически отображать поля для ввода штрафов под диапазонами
- для критериев воды, тошноты, ципфа и ключевых слов  нужны чекбоксы, чтобы можно было их явным образом включить / выключить

Я понимаю, что такая постановка может показаться сложной, поэтому буду рад ответить на ваши вопросы!

2020-08-28 18:16 UTC, levi218 commented
зачем нужны чекбоксы для включения / выключения критериев воды, тошноты, zipf и ключевых слов, если мы можем использовать вертикальный слайдер и изменить вес на 0?
если мы их выключим, то должны скрыть их с вертикального слайдера?

2020-09-01 07:04 UTC, zmm commented
Про слайдер - хорошая идея, давайте так и сделаем. 
Касательно новой модели данных - ее уже частично начал делать Василий вот тут https://github.com/OSLL/sw-auto/pull/108

2020-09-04 12:43 UTC, zmm commented
Все хорошо, мелкие замечания:
- все-таки критериям Ципф, тошнота,водность и ключевые слова нужны чекбоксы или иной способ отключения (особенно неудобно выключать водность в текущем варианте)
- нужно ограничить вывод двумя знаками после запятой 
![image](https://user-images.githubusercontent.com/717575/92240421-4a418f80-eec5-11ea-9aa8-509a99447efa.png)
- нужно выделить жирным шрифтом названия словарей 
![image](https://user-images.githubusercontent.com/717575/92240503-680ef480-eec5-11ea-87d4-960d9efa7901.png)

2020-09-08 15:46 UTC, merged