Add result settings flexibility
EduardBlees/Master-s-thesis pull request #68
Opened 2020-03-11 16:55 UTC by SWaoter

Вместо захардкоженных весовых коэффициентов из appsettings.json, добавлена возможность изменять эти веса через веб-интерфейс. Сделано по аналогии с тем, как сейчас производится настройка анализа статьи.

2020-03-11 19:03 UTC, vjkuznetsov commented
1. Может быть стоит объединить четыре поля в одну модель, чтобы не перегонять из метода в метод россыпь аргументов? И сразу же сделать их числовыми, чтобы не использовать приведение типов.

2. Насколько я понимаю, метод UploadFile предполагается для использования студентами. А изменение весовых коэффициентов - это прерогатива преподавателя (что будет, если студент выставит errorCost в ноль?). Возможно, следует разделить эти функции на два отдельных метода контроллера (или даже на разные контроллеры). Методы для преподавателя должны будут вызываться только после авторизации.

2020-03-20 11:36 UTC, SWaoter commented
Добавил авторизацию и разделение по ролям. Теперь когда пользователь заходит на страницу, ему будет предложена возможность зарегистрироваться либо студентом, либо преподавателем. Преподаватель пока что имеет возможность только добавлять наборы критериев для оценки. Студент привязывается к преподавателю и имеет возможность использовать при проверке свой работы пользоваться только его настройками оценивания. Пока что не работает с Докером( из-за того, что требуется доступ к MSSQL серверу).

2020-04-10 09:00 UTC, zmm requested changes
docker-compose build 

.....


 ---> Running in 37d0fe783a97
DAL/ResultRepository.cs(31,13): warning CS0618: 'MongoClientSettings.Credentials' is obsolete: 'Use Credential instead. Using multiple credentials is deprecated.' [/src/TestWebApp/WebPaperAnalyzer.csproj]
Test run for /src/Test/bin/Release/netcoreapp2.2/Test.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 16.0.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   EndToEndSuccessTest
Error Message:
 Test method Test.WebPaperAnalyzerTest.EndToEndSuccessTest threw exception: 
System.TimeoutException: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/mongo:27017" }", EndPoint: "Unspecified/mongo:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ResolveEndPointsAsync(EndPoint initial)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastUpdateTimestamp: "2020-04-10T08:57:03.9007543Z" }] }.
Stack Trace:
    at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedAsync(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Clusters.Cluster.SelectServerAsync(IServerSelector selector, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterSeverSelctionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.StartImplicitSessionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.ToListAsync[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at WebPaperAnalyzer.Models.ApplicationContext.GetCriteria() in /src/TestWebApp/Models/ApplicationContext.cs:line 57
   at WebPaperAnalyzer.Controllers.HomeController.UploadFile(IFormFile file, String titles, String paperName, String refsName, String criterionName) in /src/TestWebApp/Controllers/HomeController.cs:line 72
   at Test.WebPaperAnalyzerTest.EndToEndSuccessTest() in /src/Test/WebPaperAnalyzerTest.cs:line 115

Standard Output Messages:
 
 
 
 elapsed: 00:00:00.0006926, _TreeDictionary.Trim();


Failed   EndToEndUnsupportedFileTypeTest
Error Message:
 Test method Test.WebPaperAnalyzerTest.EndToEndUnsupportedFileTypeTest threw exception: 
System.TimeoutException: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/mongo:27017" }", EndPoint: "Unspecified/mongo:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ResolveEndPointsAsync(EndPoint initial)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastUpdateTimestamp: "2020-04-10T08:57:36.3358173Z" }] }.
Stack Trace:
    at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedAsync(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Clusters.Cluster.SelectServerAsync(IServerSelector selector, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterSeverSelctionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.StartImplicitSessionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.ToListAsync[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at WebPaperAnalyzer.Models.ApplicationContext.GetCriteria() in /src/TestWebApp/Models/ApplicationContext.cs:line 57
   at WebPaperAnalyzer.Controllers.HomeController.UploadFile(IFormFile file, String titles, String paperName, String  [...]

2020-04-17 09:27 UTC, zmm requested changes
1. Размер кнопок на всех страницах и отступ слева и справа 
![image](https://user-images.githubusercontent.com/717575/79553265-e7319680-80a4-11ea-9201-900cac545e18.png)

2. Logout button

3. Ничего не происходит при добавлении критерия + нет клиентской валидации значений (не понятно, какими они должны быть?) 
http://localhost:4444/StudentTeacher/TeacherAddCriterion

4. Как можно отредактировать значения критериев?

5. Где можно посмотреть список уже созданных критериев пользователя?

6. Давайте добавим в настройки также разброс для каждого из критериев

7. Будучи студентом, не могу перейти к списку своих прошедших проверок 

![image](https://user-images.githubusercontent.com/717575/79554517-d1bd6c00-80a6-11ea-990b-134ed153af6b.png)

2020-05-01 15:25 UTC, merged